### ISSUE TITLE
change WOAS to WAVE_ON_A_STRING

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-on-a-string#103]
There's no reason that this sim should be using a different convention, and it's resulting in WOAS-specific code in the string.js plugin (see https://github.com/phetsims/chipper/issues/83). Please change WOAS to WAVE_ON_A_STRING throughout.

**Comment by pixelzoom** [comment]
This should be a simple matter of changing 'WOAS' to 'WAVE_ON_A_STRING' in wave-on-a-string-config.js, then doing a global replace of 'WOAS/' with 'WAVE_ON_A_STRING/'.  But when I do that, I get requirejs errors, e.g.: 

> Uncaught Error: Script error for: WAVE_ON_A_STRING/view/WOASScreen
http://requirejs.org/docs/errors.html#scripterror

So perhaps there's some more cleverness going on here. If that's the case, all the more reason to change this.

**Comment by pixelzoom** [comment]
Must've been a browser caching issue. I made the changes, cleared cache, and restarted the browser. Then WAVE_ON_A_STRING works fine with no errors.  Assigning to @jonathanolson for review.

**Comment by ariel-phet** [comment]
This sim is published, and no further issues reported, closing
