### ISSUE TITLE
use PhetColorScheme.RED_COLORBLIND ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-on-a-string#105]
Beads are 'red', see TheStringNode:

> 33 var redBead = new Circle( options.radius, { fill: 'red', stroke: 'black', lineWidth: 0.5, children: [ highlightCircle ], scale: scale } );

Should they be using PhetColorScheme.RED_COLORBLIND?

Might also take a look at the handle of the wrench. It's not pure red, but it's also not color-blind red. So the black in its center may or may not disappear.

**Comment by ariel-phet** [comment]
No colorblind issues seen when checking gray scale and Protanopia and Deuteranopia

Closing
