### ISSUE TITLE
unused strings

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-on-a-string#109]
```
% grunt
...
>> Unused string: key=WAVE_ON_A_STRING/paused, value=Paused
>> Unused string: key=WAVE_ON_A_STRING/resetTimer, value=Reset
...
```

**Comment by jonathanolson** [comment]
Fixed. Does this warrant a redeploy, due to how rosetta works?

**Comment by pixelzoom** [comment]
Unclear, unresolved discussion in https://github.com/phetsims/tasks/issues/460#issuecomment-170680504.  @jbphet may be able to clarify.

**Comment by jonathanolson** [comment]
Closing, @jbphet noted that a sim with unused strings (bending-light) did not have those unused strings show up in the rosetta interface.
