### ISSUE TITLE
Long string test

### ISSUE THREAD

**Issue by BryceAG** [phetsims/wave-on-a-string#110]
Test device:
Bates

Operating System:
Windows 7

Browser:
Google Chrome

Problem description:
Numerous overlaps. The thing that the left end of the string is attached to (in any of the modes) covers the buttons and words for slow motion or normal speed. The right end selector covers the restart button, and the bottom box is a mess. The buttons are still clickable, but there is overlap with the tension selector and the reference line button

Steps to reproduce:
use &stringTest=long

Severity:
![image](https://cloud.githubusercontent.com/assets/15327201/12462218/578bc28e-bf7a-11e5-8499-ff57c6a8248b.png)

Screenshots:

Troubleshooting information (do not edit):
Name: 12345678901234567890123456789012345678901234567890
URL: http://phettest.colorado.edu/wave-on-a-string/wave-on-a-string_en.html?ea&brand=phet&stringTest=long
Version: 1.0.0 (require.js)
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Language: en-US
Window: 1366x667
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 9 uniform: 253
Texture: size: 8192 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

For phetsims/tasks#479

**Comment by BryceAG** [comment]
The bottom box gets worse in the other modes.
![image](https://cloud.githubusercontent.com/assets/15327201/12462412/6726fa78-bf7b-11e5-8b46-1ff59ed04dfe.png)

**Comment by jonathanolson** [comment]
Done, screenshots:

Double:
![wave-on-a-string-double](https://cloud.githubusercontent.com/assets/480878/13328231/d884b200-dbaa-11e5-9678-bda8d503253a.PNG)

Long:
![wave-on-a-string-long](https://cloud.githubusercontent.com/assets/480878/13328236/de534a2a-dbaa-11e5-95f3-ce86ee83525f.PNG)

Closing.
