### ISSUE TITLE
Reduce size of radio buttons to more consistent with other sims

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/wave-on-a-string#113]
The radio buttons in WOAS are quite large, it would be good to reduce them to proportions that better match our more modern conventions.

See for instance http://phet.colorado.edu/sims/html/beers-law-lab/latest/beers-law-lab_en.html

I think a good "rule of thumb" is to make the diameter of the radio button match the height of the first capital letter in the label. For instance the "M" in "Manual"

**Comment by ariel-phet** [comment]
@jonathanolson if this is a fix that is very quick and would require minimal testing (I know the RC is already out) I would like to see this one pixel polish for this release. If not, please mark as priority deferred

**Comment by jonathanolson** [comment]
@ariel-phet, can you test on phettest to see if the appearance looks good?

I agree that it would need minimal testing, and I can move the change over to the RC when it looks good.

**Comment by ariel-phet** [comment]
Yes much better @jonathanolson, please move to RC and then close this issue.

**Comment by jonathanolson** [comment]
> please move to RC

To the branch, or want rc-2?

**Comment by ariel-phet** [comment]
Your call...I don't believe we need an rc-2 unless and blocking issues are found.

**Comment by jonathanolson** [comment]
Moved commit to RC branch, closing.
