### ISSUE TITLE
Consider more precise control of tension

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/wave-on-a-string#115]
From a teacher who wrote phethelp:

> Is there any precise way to control and/or monitor the value of the tension setting in "Waves on a String", as there is for "Amplitude", "Frequency", and "Pulse width"?  While it seems that the tension can assume many different values, there does not seem to be any way to have a quantitative idea (e.g., percentage of the way from "Low" to "High") as to what the value it.

Seems worthy of discussion next time we revisit this sim (for instance if we add an energy screen or perform some of the other suggested enhancements).

**Comment by oliver-phet** [comment]
Another teacher wrote into phethelp Sep 21:

> Hello, I have been using the Phet site to teach waves to my Physics 1 class for several years. The new HTML Waves no longer differentiates the levels of tension on the site.  It now only has 3 levels…low med and high. I do not think it is scaled properly. Thanks. Laura Zinszer

**Comment by ariel-phet** [comment]
The second teacher comment is mainly requesting more granularity to the slider (which would be an easy change). The first request for more quantitative tension is a bit trickier.

**Comment by arouinfar** [comment]
@oliver-phet I can write a response to the 2nd teacher when I'm back in the office tomorrow. 

@ariel-phet I definitely think we should increase the range of the tension slider. As I said in #114:

>After going through this exercise, however, I wonder if we have too severely limited the ability of the HTML5 sim to address learning goals related to tension and speed. It certainly supports learning goals related to the qualitative relationship, but the Flash version can get more at the quantitative relationship (if the slider scaling is known). I wouldn't be surprised if some teachers deliberately use the Flash version because it has 11 tension notches, as opposed to 3 in the HTML5 version.

**Comment by oliver-phet** [comment]
The second teacher send another email:

> One of the important big ideas is as students increase the tension, the velocity increases. I have created the following documents. If you used a tension scale 1-5 that might allow for additional accuracy.
[Day 7 Amplitude of a Transverse Wave.pdf](https://github.com/phetsims/wave-on-a-string/files/485785/Day.7.Amplitude.of.a.Transverse.Wave.pdf)
[Day 8 Frequency of a Transverse Wave.pdf](https://github.com/phetsims/wave-on-a-string/files/485786/Day.8.Frequency.of.a.Transverse.Wave.pdf)

**Comment by arouinfar** [comment]
This has been addressed in #116 and is awaiting sim redeploy.
