### ISSUE TITLE
User reported issue: animation slows every 6 seconds

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/wave-on-a-string#124]
Test device: HP Pavilion dv6 laptop

Operating System: Windows 7

Browser:Chrome

Problem description: Wave animation slows briefly every 6 seconds

Steps to reproduce: Set to oscillate, No End; glitch does not seem to depend on amplitude or frequency.  Happens very reliably every 6 seconds.

Severity: Minor - just odd that it happens, and distracting when trying to count cycles to do lab

Screenshots:

Troubleshooting information (do not edit):
Name: ‪Wave on a String‬
URL: https://phet.colorado.edu/sims/html/wave-on-a-string/latest/wave-on-a-string_en.html
Version: 1.1.6 2017-02-04 16:30:00 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Language: en-US
Window: 1325x772
Pixel Ratio: 0.75/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 9 uniform: 253
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"9457f36a","branch":"HEAD"},"babel":{"sha":"7f243c48","branch":"master"},"brand":{"sha":"d9e64f42","branch":"HEAD"},"chipper":{"sha":"23ec53ef","branch":"HEAD"},"dot":{"sha":"da78031b","branch":"HEAD"},"joist":{"sha":"03847a9a","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"c472f6f8","branch":"HEAD"},"scenery":{"sha":"b34b4fea","branch":"HEAD"},"scenery-phet":{"sha":"71a9c763","branch":"HEAD"},"sherpa":{"sha":"b999987e","branch":"HEAD"},"sun":{"sha":"2b83e994","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"},"wave-on-a-string":{"sha":"67794316","branch":"HEAD"}}

**Comment by ariel-phet** [comment]
@oliver-phet I have a windows 7 machine, tried this on Chrome, unable to reproduce.

Perhaps ask the user how old their computer is? This might just be an old hardware issue (and not much we can do in that case)

**Comment by oliver-phet** [comment]
> It's a 4-5 year old laptop, so I'll blame it on HP. I haven't seen it in school, but I figured I'd report it in case it was more widespread. 
Thanks for quick response. 
I LOVE your site. 
Any chance on a longitudinal standing wave app?  Walter Fendt used to have one, but it died.

**Comment by oliver-phet** [comment]
Closing for the time being. If another user reports similar behavior, will reopen.
