### ISSUE TITLE
User Request: Finer tuning capability with the frequency

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-on-a-string#129]
Mentioned in https://groups.google.com/d/msg/developing-interactive-simulations-in-html5/O1cJem3VW18/Dup8UwJ7AQAJ

> Hi, I would like to find someone that can help me with the Wave on a String app? Would really like a finer tuning capability with the frequency. 
> You can email me at [...]
> Thank you

Assigned to @ariel-phet for next steps.

**Comment by arouinfar** [comment]
Just throwing in my 2 cents -- the frequency is already adjustable in steps of 0.01 Hz, which seems perfectly adequate to me. Without knowing more about the user's desired use-case or motivation for the change, I'd be inclined to pass.

**Comment by arouinfar** [comment]
I sent the following email to the user:
> I’d like to thank you for your recent suggestion to allow for finer tuning of the frequency in our Wave on a String simulation.
>
>The design team is currently considering your suggestion, but we would like to hear more about your goals for this particular modification. Additionally, we’d like to know what precision level you’d like to see (0.001 Hz, for example?).
>
>Looking forward to hearing back from you.

**Comment by arouinfar** [comment]
The user's response (some personal details have been omitted):

>Yes, 0.001 Hz would be fantastic.
>
>As a former computer programmer from the 1980s when computers first came into use, I understand that increasing the fine tuning of the driving frequency may be easier then my next request. and that is the ability to set the length of the string for one wavelength other than changing the tension.  
>
> I am researching Nikola Tesla's wireless energy transmission and discovered his plans for using standing waves to do so.
If you are interested in this information see the link below for one of his patents.
https://en.wikisource.org/wiki/Canadian_patent_142352
> 
>Note what he says in that patent:
>>"Still another fact now of common knowledge is that when electrical waves or oscillations are impressed upon such a conducting-path as a metallic wire reflection taken place under certain conditions from the end of the wire, and in consequence of the interference of the impressed and reflected oscillations the phenomenon of "stationary waves" with maxima and minima in definite fixed positions is produced." 
> 
>Using your Wave on a String app I have proven that using a 1/2 wavelength (can  explain more latter if you which) I am getting a 3 db gain per cycle of the input drive and I believe his bifilar pancake coil would be ideal for using as an energy generator as the center tap is centered on the antinode.
 >
>I have also proven that for a 1/4 wavelength, which would us an open end, and what he planned on using for transmitting thru the earth, has a 6 db gain of the driving power per cycle.
>
>I will give you a link for a video that I did using the app.
Please keep in mind this was the second video I did where I am talking in it and I make some mistakes which I do correct for the most part. I plan on redoing it and would love to be able to have the fine tuning to do so. But please, if you can make both changes, but would take longer to add adjustment for string length, could you do the fine tuning first?

It's still not particularly clear to me what the extra digit would actually do for the user, but this use case is certainly beyond the scope of the learning goals, so closing.
