### ISSUE TITLE
User suggestion: 2 pulse modes, detector tool

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/wave-on-a-string#131]
> Suggestion for Waves on a String:
> 
> == In Pulse mode have two buttons, one for an up pulse and one for a down.
> 
> == A detector tool that can be used to look at the time evolution of a particular location on the string.
> This would provide “history” graphs along with the “snapshots” you can take by freezing the motion.
> I imagine that you would identify a particular spot on the string and then have a “chart recorder” display of position vs. time.
> There is a similar tool in Wave Interference where you an watch oscillations in the water at particular location.  (see screenshot)
![image](https://user-images.githubusercontent.com/5090275/51703642-1bb6bf80-1fd4-11e9-994f-c310835617f6.png)

**Comment by arouinfar** [comment]
Neither one of these suggestions strikes me as critical to the core learning goals of the simulation.  My inclination would be to defer this issue and maybe give it another year to see if other similar requests pop up. Does that sound reasonable @ariel-phet?

> In Pulse mode have two buttons, one for an up pulse and one for a down.

If we added a down pulse, it could be used to create destructive interference which might be nice. There is certainly room on the pulse source to add a second button, though it does muddy the UI a bit. 

<img src="https://user-images.githubusercontent.com/8419308/81330472-5cb5d480-905d-11ea-8a97-17270723ecf8.png" width=150>

> A detector tool that can be used to look at the time evolution of a particular location on the string.

I think this goal is better served by Waves Intro or Wave Interference. At the time of the user's request, these sims hadn't yet been published.

If we added such a tool, I think the probe locations would need to be restricted to the center line, similar to what we did in the side-view of water in wave-interference.

![image](https://user-images.githubusercontent.com/8419308/81331944-8d970900-905f-11ea-9b59-82f32c29f508.png)

![image](https://user-images.githubusercontent.com/8419308/81331917-8839be80-905f-11ea-854b-e832d529dd1e.png)

**Comment by ariel-phet** [comment]
@arouinfar in the condition where you have a fixed end, you can produce destructive interference.

I actually think neither of these suggestions is particularly appropriate for WOAS and the learning goals are much better handled with Waves Intro or such. I think we are safe to close. 

Closing
