### ISSUE TITLE
use common-code slider

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-on-a-string#132]
While working on SUN/Slider changes in https://github.com/phetsims/sun/issues/478, I discovered that wave-on-a-string has its own slider implementation `WAVE_ON_A_STRING/Slider`.  The screenshot below shows the 2 places where it's used.   This should definitely be replaced with `SUN/Slider`, or possibly `SCENERY_PHET/NumberControl`.    And this is a prerequisite to a11y and phet-io instrumentation.

**Comment by jonathanolson** [comment]
Using NumberControl now, thanks!
