### ISSUE TITLE
Use Stopwatch and StopwatchNode

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-on-a-string#136]
From https://github.com/phetsims/gas-properties/issues/170, we would like to update Waves on a String to use new support in scenery-phet for Stopwatch and StopwatchNode.  I've made these changes locally and, after pushing, will use this issue for review.

**Comment by samreid** [comment]
@jonathanolson can you please review at your convenience?

**Comment by jonathanolson** [comment]
Looks good, thanks!
