### ISSUE TITLE
Does the end (window/pole/clamp) node need to be instrumented?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/wave-on-a-string#142]
Due to layering, the endNode does not contain the window, and it has a few different components. Can we ignore this and not instrument, or do we want to be able to hide different parts independently? That would need more integrated support.

**Comment by arouinfar** [comment]
We do not need to be able to hide the parts independently. In fact, it would look super strange to end the endNode altogether. I don't see any need to instrument the `endNode`. The important part is which end is selected, which is already covered under `endTypeProperty`. Closing.
