### ISSUE TITLE
Possible to lose components in PhET-iO master iframes

### ISSUE THREAD

**Issue by ghost** [phetsims/wave-on-a-string#144]
For ES6 testing.

I saw this in the text area wrapper, but I don't think it generalizes to all iframes, i.e. I tried to get this to happen on https://phet-dev.colorado.edu/html/wave-on-a-string/1.1.22-rc.1/wave-on-a-string_en-iframe.html and it didn't work.

It does, however, seem to work for Wave on a String PhET-iO wrappers on master.

![issue](https://user-images.githubusercontent.com/31285590/75933179-8ae91f00-5e36-11ea-8193-d69b62647754.gif)

I'm wondering if this generalizes to other sims with similar components. I'll update the issue if it does.

Update: You can also lose the vertical ruler.

**Comment by jonathanolson** [comment]
Don't need an iframe, this happens just in general for the simulation (reproduced by running it locally). Should we change things so it's not possible to drag things away?

**Comment by ariel-phet** [comment]
@jonathanolson yes - you shouldn't be able to drag things below the nav bar.

**Comment by jonathanolson** [comment]
This should now be handled properly (and converted the sim off SimpleDragHandler). @ariel-phet does the current behavior for the rulers and reference line work well?

**Comment by ariel-phet** [comment]
All seems good. Closing
