### ISSUE TITLE
Updates to slider range, constrainValue

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-on-a-string#148]
This stems from #147, but is a general design change so creating a separate issue.

Amplitude:
- [x] Increase range to 1.3 cm
- [x] Use constrainValue to snap thumb in steps of 0.1 cm

Frequency:
- [x] Use constrainValue to snap thumb in steps of 0.1 Hz

Pulse Width:
- [x] Use constrainValue to snap thumb in steps of 0.1 s

Damping:
- [x] Use constrainValue to snap thumb in steps of 5%

**Comment by jonathanolson** [comment]
Should be implemented in the above commit, can you verify?

**Comment by arouinfar** [comment]
@jonathanolson the ranges and thumb snapping looks good in master, but the tweaker increment should still be the smallest possible step size.

- [ ] Amplitude: 0.01 cm
- [ ] Frequency: 0.01 Hz
- [ ] Pulse Width: 0.01 s
- [ ] Damping: 1%
- [ ] Tension: 1%

**Comment by jonathanolson** [comment]
I believe that should be fixed, apologies! NumberControl is generally set up to use the same step sizes for the buttons and slider.

**Comment by arouinfar** [comment]
Looks great, thanks @jonathanolson!
