### ISSUE TITLE
Pulse wave amplitude is inconsistent with low tension and low pulse width. 

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/wave-on-a-string#44]
The amplitude of the pulse wave is inconsistent in a succession of pulses with the following conditions:
Amplitude: 3 cm
Pulse width: 0.16s
Damping: none 
Tension: low
The succession of wave pulses vary in height.
![screen shot 2014-01-31 at 2 39 21 pm](https://f.cloud.github.com/assets/5631059/2055127/88481102-8ac0-11e3-93fb-5ed8b64b2a0f.png)

**Comment by ariel-phet** [comment]
parameters in published version do not allow this condition, issue not observed. Closing.
