### ISSUE TITLE
Wrench does not appear on IE11 without workaround (IE9 is OK)

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/wave-on-a-string#74]
Name: Wave on a String
URL: http://localhost:8080/wave-on-a-string/wave-on-a-string_en.html
Version: 0.0.0-dev.9
Features missing: touch, fullscreen
Flags: pointerEnabled, msPointerEnabled
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E; rv:11.0) like Gecko
Language: en-US
Window: 1920x1105
Pixel Ratio: 1/1
WebGL: WebGL 0.94
GLSL: WebGL GLSL ES 0.94
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true

![woas-no-wrench](https://cloud.githubusercontent.com/assets/480878/4071241/a4b7e39e-2e6c-11e4-9b28-7d17126d06a2.PNG)

but when browsing to the SVG file:
![woas-no-wrench-ok](https://cloud.githubusercontent.com/assets/480878/4071247/be2a0ce4-2e6c-11e4-951e-5a3cd2cce533.PNG)

And it works on IE9 in our VM:
![woas-no-wrench-ie9](https://cloud.githubusercontent.com/assets/480878/4071252/d2bed46e-2e6c-11e4-9256-dc5000120d82.PNG)

IE11 is reporting 0x0 for the image bounds.

**Comment by ariel-phet** [comment]
This issue seems no longer to be relevant, closing
