### ISSUE TITLE
Slow performance Win 8 FF 32.0 in Oscillate with High frequency.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/wave-on-a-string#92]
The sim slows down substantially when the frequency = 3.00 Hz. Not nearly as smooth as the Java version.

Troubleshooting information (do not edit):
Name: Wave on a String
URL: http://www.colorado.edu/physics/phet/dev/html/wave-on-a-string/0.0.0-dev.14/wave-on-a-string_en.html
Version: 0.0.0-dev.14
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:32.0) Gecko/20100101 Firefox/32.0
Language: en-US
Window: 1366x657
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 8192 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by ariel-phet** [comment]
Current performance good on Win 7 FF, no issues have been submitted since publication, closing
